import '../models/scheme_of_work.dart';
import '../models/syllabus_models.dart';
import 'required_core_topic_service.dart';
import 'subject_content_repository.dart';
import 'topic_search_service.dart';

/// One resolved "Required Core Topic" (2026-09-12, per explicit request) —
/// a teacher-named topic ("rise and fall of Shaka Zulu") the generated
/// scheme didn't directly show, resolved into a real [SchemeOfWorkEntry]
/// ready to slot into the document.
class RequiredCoreTopicResult {
  final String phrase;
  final SchemeOfWorkEntry entry;

  /// True when [entry] is a REAL syllabus topic/sub-topic that already
  /// exists elsewhere in this subject (just not in this term's scheme) —
  /// its topic/sub-topic id is real, so lesson-history/progress logging
  /// treats it exactly like any other real topic. False means [entry]'s
  /// topic is synthetic (its competencies/objectives were generated by AI,
  /// grounded in on-device material when any was found) and must be
  /// excluded from that logging — see SchemeOfWorkDocumentScreen's own use
  /// of this.
  final bool isRealSyllabusTopic;

  /// Where the content came from, for the confirmation shown to the
  /// teacher — never shown inside the generated document itself.
  final RequiredCoreTopicSource source;

  const RequiredCoreTopicResult({
    required this.phrase,
    required this.entry,
    required this.isRealSyllabusTopic,
    required this.source,
  });
}

enum RequiredCoreTopicSource {
  /// A real topic/sub-topic already in this subject's own syllabus —
  /// used exactly as authored, no AI involved.
  syllabus,

  /// Not in the syllabus itself — AI wrote proper syllabus-style
  /// competencies/objectives for it, grounded in real material found in
  /// the Subject Content Database.
  aiGroundedInSavedMaterial,

  /// Not in the syllabus, and nothing was found on-device either — AI
  /// researched it online and wrote proper syllabus-style competencies/
  /// objectives from that research.
  aiResearchedOnline,
}

/// How many of the CURRENT scheme's own entries "Required Core Topics"
/// should push off to next term, given [requestedCount] newly-resolved
/// topics and [currentEntryCount] entries already in the scheme. Normally
/// equal to [requestedCount] (1:1, per explicit request), but NEVER more
/// than [currentEntryCount] - 1 — a real, reported bug: a term with few
/// entries left (a class resumed near the end of term, a short "Select
/// Own Topics" pick) could have fewer entries than requested topics, so
/// requesting 3 emptied the WHOLE scheme down to just those 3, reported as
/// "only the topics added by the button, everything else gone". Always
/// leaves at least one of the scheme's own entries (0 only when the
/// scheme was already empty).
int requiredCoreTopicPushCount(int requestedCount, int currentEntryCount) {
  if (currentEntryCount <= 0 || requestedCount <= 0) return 0;
  final maxPushable = currentEntryCount - 1;
  return requestedCount.clamp(0, maxPushable);
}

/// Searches, for each phrase, in order — cheapest and most trustworthy
/// first: this subject's WHOLE syllabus (every term, not just the one
/// being scheduled — the whole point is surfacing content "hidden" inside
/// a bigger topic or a different term), then the on-device Subject
/// Content Database, then — only if neither finds anything — one real
/// online search via [RequiredCoreTopicService]. Entirely offline until
/// that last step.
class RequiredCoreTopicResolver {
  RequiredCoreTopicResolver({
    TopicSearchService? topicSearchService,
    SubjectContentRepository? subjectContentRepository,
    RequiredCoreTopicService? aiService,
  })  : _topicSearch = topicSearchService ?? TopicSearchService(),
        _subjectContent = subjectContentRepository ?? SubjectContentRepository(),
        _aiService = aiService ?? RequiredCoreTopicService();

  final TopicSearchService _topicSearch;
  final SubjectContentRepository _subjectContent;
  final RequiredCoreTopicService _aiService;

  int _syntheticIdCounter = -900000;
  int _nextSyntheticId() => _syntheticIdCounter--;

  /// [phrases] should already be split/trimmed/capped (see the screen's own
  /// comma-splitting) — up to 3, per explicit request. [existingEntries] is
  /// this term's current scheme, used only to avoid re-adding a real
  /// syllabus topic that's already in it.
  Future<List<RequiredCoreTopicResult>> resolve({
    required List<String> phrases,
    required SyllabusTemplate template,
    required List<SchemeOfWorkEntry> existingEntries,
  }) async {
    final results = <RequiredCoreTopicResult?>[for (final _ in phrases) null];
    // Every phrase not resolved directly from the real syllabus goes
    // through AI — real, reported bug fixed here (2026-09-13): this used
    // to short-circuit whenever the Subject Content Database had ANY
    // matching material, synthesizing a generic filler sentence
    // ("Explain X, drawing on the material already saved on this
    // device.") instead of a real, syllabus-connected specific outcome.
    // Now on-device material is passed to the AI as GROUNDING, not as a
    // shortcut that skips writing proper content — the actual wording
    // always comes from real generation, whether grounded in local
    // material or fresh research.
    final aiQueue = <int>[];
    final localContexts = <String?>[for (final _ in phrases) null];

    final existingIds = {for (final e in existingEntries) (e.topic.id, e.subTopic?.id)};

    for (var i = 0; i < phrases.length; i++) {
      final phrase = phrases[i];

      // 1. The whole subject syllabus — every term, so a topic "hidden"
      // under a bigger one, or scheduled in a different term, still
      // surfaces, with its own real, authored competencies/objectives.
      final search = _topicSearch.searchWithinTemplate(template, phrase, limit: 1);
      if (search.results.isNotEmpty) {
        final hit = search.results.first.entry;
        if (!existingIds.contains((hit.topic.id, hit.subTopic?.id))) {
          results[i] = RequiredCoreTopicResult(
            phrase: phrase,
            entry: hit,
            isRealSyllabusTopic: true,
            source: RequiredCoreTopicSource.syllabus,
          );
          continue;
        }
      }

      // 2. Not in the syllabus — see if the Subject Content Database has
      // real material to ground the AI's writing in (cheaper and more
      // reliable than a fresh online search, but never a substitute for
      // actually generating a proper outcome statement).
      try {
        final hits = await _subjectContent.searchContent(phrase, maxResults: 3);
        if (hits.isNotEmpty) localContexts[i] = hits.first.excerpt;
      } catch (_) {
        // Just means no local grounding for this one — AI still runs.
      }
      aiQueue.add(i);
    }

    if (aiQueue.isNotEmpty) {
      final aiResults = await _aiService.generate(
        phrases: [for (final i in aiQueue) phrases[i]],
        localContexts: [for (final i in aiQueue) localContexts[i]],
        subjectName: template.subject.name,
        gradeName: template.grade.name,
        curriculumName: template.curriculum.name,
        syllabusContext: _buildSyllabusContext(template),
      );
      // Match each requested phrase back to its AI result primarily by
      // POSITION (the function is asked to answer in order and normally
      // does), falling back to matching the AI's own echoed `phrase` text
      // — real, reported bug fixed here: an all-or-nothing positional
      // gate used to silently drop a topic entirely whenever the model
      // paraphrased a phrase or returned fewer entries than asked.
      for (var pos = 0; pos < aiQueue.length; pos++) {
        final i = aiQueue[pos];
        final phrase = phrases[i];
        bool usable(RequiredCoreTopicAiResult? r) =>
            r != null && r.name.trim().isNotEmpty && r.competencies.isNotEmpty && r.objectives.isNotEmpty;

        RequiredCoreTopicAiResult? ai = pos < aiResults.length ? aiResults[pos] : null;
        if (!usable(ai)) {
          final byPhrase = aiResults.where(
            (r) => r.phrase.trim().toLowerCase() == phrase.trim().toLowerCase() && usable(r),
          );
          if (byPhrase.isNotEmpty) ai = byPhrase.first;
        }
        // Genuinely couldn't produce real content for this one — skip it
        // rather than inventing a generic filler row. The confirmation
        // message names whichever phrases this happens to, so it's never
        // silent.
        if (!usable(ai)) continue;
        final name = ai!.name.trim();
        final topic = Topic(
          id: _nextSyntheticId(),
          sequenceNumber: 0,
          name: name,
          description: ai.description,
          competencies: [
            for (var c = 0; c < ai.competencies.length; c++)
              Competency(id: _nextSyntheticId(), sequenceNumber: c + 1, description: ai.competencies[c]),
          ],
          objectives: [
            for (var o = 0; o < ai.objectives.length; o++)
              LearningObjective(id: _nextSyntheticId(), sequenceNumber: o + 1, description: ai.objectives[o]),
          ],
        );
        results[i] = RequiredCoreTopicResult(
          phrase: phrase,
          entry: SchemeOfWorkEntry(
            weekNumber: 0,
            topic: topic,
            objectives: topic.objectives,
            competencies: topic.competencies,
          ),
          isRealSyllabusTopic: false,
          source: localContexts[i] != null
              ? RequiredCoreTopicSource.aiGroundedInSavedMaterial
              : RequiredCoreTopicSource.aiResearchedOnline,
        );
      }
    }

    return results.whereType<RequiredCoreTopicResult>().toList();
  }

  /// A short, real sample of this syllabus's own topic names and a few
  /// objectives — grounds the AI research in what this subject/level
  /// actually covers, per explicit request ("look at what the syllabus
  /// mentions about those topics and its objectives").
  String _buildSyllabusContext(SyllabusTemplate template) {
    final topicNames = <String>[];
    final objectiveSamples = <String>[];
    for (final term in template.terms) {
      for (final topic in term.topics) {
        topicNames.add(topic.name);
        if (objectiveSamples.length < 6 && topic.objectives.isNotEmpty) {
          objectiveSamples.add(topic.objectives.first.description);
        }
        for (final sub in topic.subTopics) {
          topicNames.add(sub.name);
        }
      }
    }
    final parts = <String>[];
    if (topicNames.isNotEmpty) parts.add('Topics this syllabus covers: ${topicNames.take(25).join(', ')}.');
    if (objectiveSamples.isNotEmpty) parts.add('Example stated objectives: ${objectiveSamples.join(' ')}');
    return parts.join('\n');
  }
}
