# google_mlkit_text_recognition references optional non-Latin script
# recognizer classes (Chinese/Japanese/Korean/Devanagari) that only exist
# if the corresponding script-specific ML Kit dependency is also added.
# This app only uses Latin-script recognition, so these are genuinely
# absent, not a real problem — R8 needs to be told that's expected rather
# than treating it as a missing-class error. Generated by R8 itself
# (build/app/outputs/mapping/release/missing_rules.txt) after a real
# release build failure, not guessed.
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions
